[package]
name = "macrodb"
version = "0.1.0"
edition = "2021"
authors = ["Patrick Elsen <pelsen@xfbs.net>"]
description = "Macro-generated in-memory databased for Rust"
license = "MIT"

[[bench]]
name = "single_table"
harness = false

[dependencies]
paste = "1.0.11"

[dev-dependencies]
criterion = "0.4.0"
